#!/bin/bash
# Copies the Raft/XDP lab code to all three VMs.

set -euo pipefail

GREEN='\033[0;32m'; YELLOW='\033[1;33m'; NC='\033[0m'
log()  { echo -e "${GREEN}[+]${NC} $1"; }
warn() { echo -e "${YELLOW}[!]${NC} $1"; }

NODES=("node1" "node2" "node3")
DIRS=("xdp" "protocol" "benchmark")

declare -A NODE_IP
for name in "${NODES[@]}"; do
    ip=$(multipass info "$name" | awk '/IPv4/ {print $2; exit}')
    NODE_IP[$name]=$ip
    log "$name -> $ip"
done

echo ""
warn "Raft cluster layout:"
echo "  LEADER    (node1): ${NODE_IP[node1]}"
echo "  FOLLOWER  (node2): ${NODE_IP[node2]}"
echo "  FOLLOWER  (node3): ${NODE_IP[node3]}"
echo ""

for name in "${NODES[@]}"; do
    log "Deploying to $name (${NODE_IP[$name]})..."
    multipass exec "$name" -- mkdir -p ~/electrode-lab/{xdp,protocol,benchmark}

    for dir in "${DIRS[@]}"; do
        for f in "$dir"/*; do
            [ -f "$f" ] && multipass transfer "$f" "$name":~/electrode-lab/"$f"
        done
    done

    node_id=${name#node}
    CONFIG=$(cat <<EOF
# electrode-lab Raft node config, generated by 03_deploy_raft.sh
NODE_NAME=$name
NODE_ID=$node_id
LEADER_NAME=node1
LEADER_IP=${NODE_IP[node1]}
FOLLOWER1_IP=${NODE_IP[node2]}
FOLLOWER2_IP=${NODE_IP[node3]}
RAFT_PORT=9000
CLUSTER_SIZE=3
EOF
)
    echo "$CONFIG" | multipass exec "$name" -- bash -c "cat > ~/electrode-lab/node_config.env"
    log "$name: files and config deployed."
done

echo ""
log "Deploy complete. Run: ./benchmark/run_raft_experiment.sh"
